// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/sgokul961/GO-PROJECT/pkg/api"
	"github.com/sgokul961/GO-PROJECT/pkg/config"
	"github.com/sgokul961/GO-PROJECT/pkg/db"
	"github.com/sgokul961/GO-PROJECT/pkg/handler"
	"github.com/sgokul961/GO-PROJECT/pkg/repository"
	"github.com/sgokul961/GO-PROJECT/pkg/usecases"
)

// Injectors from wire.go:

func InitializeApi(cfg config.Config) (*api.ServerHTTP, error) {
	gormDB, err := db.ConnectDatabase(cfg)
	if err != nil {
		return nil, err
	}
	adminRepositoryinterfaces := repository.NewAdminRepository(gormDB)
	adminUseCaseinterface := usecases.NewAdminUseCase(adminRepositoryinterfaces)
	adminHandler := handler.NewAdminHandler(adminUseCaseinterface)
	serverHTTP := api.NewServerHTTP(adminHandler)
	return serverHTTP, nil
}
